### ISSUE TITLE
Problème sur Fonctions d'agrégation

### ISSUE THREAD

**Issue by LePr0totype** [cpge-exercices/sql#2]
Bonjour, dans le chapitre "Fonctions d'agrégation" sur l'exercice "Concours", le programme numéro 2 ne veut pas se lancer. Quoique je mette (même rien) il donne une erreur : Erreur : near "épreuves": syntax error
Merci, bonne soirée

**Comment by fortierq** [comment]
Bonjour,
C'est étonnant car cela fonctionne chez moi (voir PJ). Pouvez-vous me montrer par une capture d'écran ? Et la console du navigateur aussi si possible (F12).
![x2](https://user-images.githubusercontent.com/49362475/232123422-c9594f7a-61c9-4f92-931a-031ca791a674.png)
![c1](https://user-images.githubusercontent.com/49362475/232123427-004b1d5b-f70b-4aeb-b33b-475786547c26.png)

**Comment by LePr0totype** [comment]
Voici les 2 captures. C'est vrai que c'est super bizarre étant donné qu'avec le reste des exos cela marche !
(Bien sur j'ai réactualisé la page) 
![image](https://user-images.githubusercontent.com/90505493/232133505-29b0f025-f100-4461-8de2-4c3ef24360b6.png)
![image](https://user-images.githubusercontent.com/90505493/232133640-21f394c0-af5b-4d00-9a65-31ad466336a5.png)
PS : je suis sur opéra GX mais comme je l'ai dit tout le reste marche donc ca ne peux pas être le navigateur le pb ?

**Comment by fortierq** [comment]
J'ai enlevé les accents dans la correction. Pouvez-vous réessayer ?

**Comment by LePr0totype** [comment]
Impec, ça marche j'ai aussi essayé sur 2 ordinateur différent. Merci beaucoup ! 
Passez un bon WE,
PS : super site pour s'entrainer !

**Comment by fortierq** [comment]
Merci et bon week-end !
